# Generated by Django 4.1.7 on 2023-04-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField(unique=True)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
    ]
