# Generated by Django 4.1.7 on 2023-04-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_table',
            },
        ),
    ]
