# Generated by Django 4.1.7 on 2023-04-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_book_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
